esphome:
  name: graef
  friendly_name: graef
  
esp8266:
  board: esp01_1m

# Logging aktivieren (für Debugging)
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api-key

ota:
  - platform: esphome
    password: !secret ota-pw
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Graef Fallback Hotspot"
    password: !secret fallback-pw
    
captive_portal:

# Benutzerdefinierte Komponente
external_components:
  - source:
      type: local
      path: my_components

# TM1651 Hub
tm1651:
  id: tm1651_hub
  pin_clk: GPIO0
  pin_dio: GPIO2

# LEDs als schaltbare Ausgänge
output:
  - platform: tm1651
    id: led_output1
    tm1651_id: tm1651_hub
    segment: 0
  - platform: tm1651
    id: led_output2
    tm1651_id: tm1651_hub
    segment: 1

light:
  - platform: binary
    name: "LED 1"
    id: led1
    output: led_output1
  - platform: binary
    name: "LED 2"
    id: led2
    output: led_output2

# Tasten als binäre Sensoren
binary_sensor:
  - platform: tm1651
    id: tm1651_key1
    name: "Taster 1"
    tm1651_id: tm1651_hub
    key_index: 0
  - platform: tm1651
    id: tm1651_key2
    name: "Taster 2"
    tm1651_id: tm1651_hub
    key_index: 1
  - platform: tm1651
    id: tm1651_key3
    name: "Taster 3"
    tm1651_id: tm1651_hub
    key_index: 2
  - platform: tm1651
    id: tm1651_key4
    name: "Taster 4"
    tm1651_id: tm1651_hub
    key_index: 3